version: '3.8'

services:
  db:
    image: mariadb:10.11 # Puoi usare anche mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      # MAGIA DOCKER: mappando la cartella "./sql" in "docker-entrypoint-initdb.d",
      # il container al primo avvio esegue tutti gli script .sql in ordine alfabetico!
      - ./sql:/docker-entrypoint-initdb.d
